INT-16 Project Overlay Component
uoftblueprint/website-v2 pull request #16
Opened 2024-03-06 19:55 UTC by elsiezhu

## Feature

[TASK: INT-16](https://linear.app/uoftblueprint/issue/INT-16/project-overlay-component)  

Description of feature or bug: Implement the project overlay/modal component according to the Figma design

### Screenshots/Recordings

<details>
  <summary> Click to expand!</summary>

  <img width="500" alt="Screenshot 2024-03-06 at 2 34 50 PM" src="https://github.com/uoftblueprint/website-v2/assets/95596800/5605b8db-68a2-4702-a7c0-8961a71d645b">
</details>

### Important Notes

- Implemented project overlay using Mantine's modal component
- Included a sample on the `/projects` page with dummy data from Figma of how the component should be used using Mantine's `useDisclosure` hook

2024-03-12 05:09 UTC, shaaaaame requested changes
HI ELSIE!!

This looks so so cool! Good job (😼)! I've left a few comments mainly to do with responsiveness. Do let me know if you have any questions :)

2024-03-12 05:09 UTC, shaaaaame commented on src/project-overlay/ProjectOverlay.tsx
> +                  href={""}
webLink and gitHubLink missing from href I think?

2024-03-12 05:09 UTC, shaaaaame commented on src/project-overlay/ProjectOverlay.tsx
> +          <Grid.Col span={4}>
I think `span={4}` is causing some issue with responsiveness (particularly <420px). Maybe change to `span={12}` if less than some number of pixels?

<details>
  <summary>Image</summary>
  
  ![image](https://github.com/uoftblueprint/website-v2/assets/81433191/d1ab9c78-858a-4a11-a5fc-dc580eba9a12)
</details>

2024-03-12 05:09 UTC, shaaaaame commented on src/project-overlay/ProjectOverlay.tsx
> +    <Grid.Col span={{ base: 10, md: 6, lg: 6 }} key={member.name}>
Breakpoints are causing TeamMember names to get cut off around (450px to 600px) and (400px to 320px). Maybe change to `span={{base: 15, sm: 10, md: 6, lg: 6}}` ?


<details>
  <summary>Image</summary>
  
![image](https://github.com/uoftblueprint/website-v2/assets/81433191/9a9b1556-c6e9-42cd-966a-d9456b50f710)</details>

2024-03-20 22:34 UTC, elsiezhu commented on src/project-overlay/ProjectOverlay.tsx
> +                  href={""}
This is just an example usage! I will add real links when I implement the page :)

2024-03-20 22:52 UTC, shaaaaame commented on src/project-overlay/ProjectOverlay.tsx
> +                  href={""}
oop sorry I wasn't clear, I meant that it's href={""} right now but should it be href={props.webLink}? if not it's ok just resolve this convo

2024-03-20 22:59 UTC, elsiezhu commented on src/project-overlay/ProjectOverlay.tsx
> +                  href={""}
Ah, I see! I will add that, thanks for clarifying!!

2024-03-20 23:12 UTC, shaaaaame approved these changes
Perfect Elsie! Great job 🐱

2024-03-23 18:44 UTC, sarahsonder approved these changes
The component is exactly like the Figma design 👀👀👀
It looks good, Elsie!

2024-03-26 23:16 UTC, merged